### ISSUE TITLE
Candidate detector looping 3x over each candidate

### ISSUE THREAD

**Issue by sukishore12** [winter-telescope/winterdrp#23]
When running pipeline, in candidate_detector log shows the logger.debug info 2x or 3x times for each candidate which is coming from the make_alerts_cutouts method. 

![image](https://user-images.githubusercontent.com/95203169/177838412-05856314-0fc5-40a4-a5b5-b207a91929b7.png)

**Comment by robertdstein** [comment]
Is it not just that each source has three cutouts (science, ref, diff)?

**Comment by virajkaram** [comment]
Yes, I fixed it in the imsub branch

**Comment by robertdstein** [comment]
OK, awesome. You should tag the commit in a comment here, then close the issue

**Comment by virajkaram** [comment]
Fixed here - 9e7a403387a834decf0d41b33daae225041797e3
