### ISSUE TITLE
Unexpected cache errors

### ISSUE THREAD

**Issue by saarahha** [winter-telescope/winterdrp#258]
**Describe the bug**
I'm attempting to run the pipeline without using a cache, but the resulting errors are not making sense / there is no support for this option without raising some error.

**Additional context (a smaller bug within the bug)**
Additionally, the cache-related documentation found in `winterdrp.data.image_data` suggests setting `export USE_WINTER_CACHE = false` for cache-less runs, but this actually returns `USE_CACHE = True` in `winterdrp.data.cache`. With the current definition in `cache.py`: 
`USE_CACHE: bool = bool(os.getenv("USE_WINTER_CACHE", "true"))`, 
the only way to have `USE_CACHE = False` would be to set `export USE_WINTER_CACHE =  ` (empty variable). So, in the following bug description, I set `USE_WINTER_CACHE` as an empty variable.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set `USE_WINTER_CACHE =  ` in your .env file.
2. In a jupyter notebook, import: `from winterdrp.pipelines.summer.summer_pipeline import SummerPipeline`
3. Run a pipeline: 
`mypipeline = SummerPipeline(selected_configurations=["test"],  night='20220402')`
`data, errorstack = mypipeline.reduce_images(catch_all_errors=False)`
4. Even though we set the code up to run without cache, see error: `CacheError: No cache dir has been set. Please set that before trying to use the cache.`

**Screenshots**
This error is coming from `winterdrp.data.cache.Cache.get_cache_dir()`. Here is the function on its own in a notebook-friendly form:
![Screen Shot 2022-12-28 at 11 24 41 AM](https://user-images.githubusercontent.com/66533667/209849637-83ff31b7-d76e-4fc1-b2be-97b26e9501a7.png)
This function depends on `USE_CACHE` and `cache_dir` (`self.cache_dir` in the original code). By messing with these two variables, we can see the resulting errors and the reasons they are unexpected (see comments):
![Screen Shot 2022-12-28 at 11 38 42 AM](https://user-images.githubusercontent.com/66533667/209851112-6f5af9de-ce5b-4c27-b5b9-329025a2fca7.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.6.0

**Comment by robertdstein** [comment]
To address the two things in turn:

Subproblem 1 is just an obvious bug. The solution I chose is to set the python variable to `True` if the environment variable is "true"/"True" or not set, and otherwise set it to `False`.

Subproblem 2 is a typo, I think. It should just be `if not USE_CACHE` rather than `if USE_CACHE`.
The additional point here is that `get_cache_dir()` should not ever be called if `USE_CACHE=False`. In the three cases you listed, case A should not happen.

This problem should be fixed by #261 .
