### ISSUE TITLE
[FEATURE] Swarp processor does not perform automatic image dimension calculation

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/winterdrp#340]
**Is your feature request related to a problem? Please describe.**
Currently, the Swarp processor is designed to specify the dimensions of the output images (either manually or calculated from the headers). This is a problem for images with large PAs, as the edges get chopped off.

**Describe the solution you'd like**
The Swarp software provides the option to calculate dimensions automatically, you just don't need to provide the IMAGE_SIZE argument and set it to 0 in the config. Not providing the option is already coded up in the `run_swarp` [function](https://github.com/winter-telescope/winterdrp/blob/f2cb552d9829414352e7bf5a23f1ff466b45184e/winterdrp/processors/astromatic/swarp/swarp.py#L34).

The problem is the Swarp processor ensures that None values are never passed to this function as arguments.
The cleanest solution I can think of would be to add a boolean argument to the processor (like `calculate_dims_in_swarp: bool = False`) and add a check to it [here](https://github.com/winter-telescope/winterdrp/blob/f2cb552d9829414352e7bf5a23f1ff466b45184e/winterdrp/processors/astromatic/swarp/swarp.py#L270). If set to true, it would call run_swarp with the relevant arguments set to None. It is up to the user to ensure that the config file is correctly configured.

**Describe alternatives you've considered**
None yet

**Additional context**
This is also relevant to WINTER  commissioning observations.

**Comment by broulston** [comment]
This should be fixed with #343 so closing
