### ISSUE TITLE
Update avro fields

### ISSUE THREAD

**Issue by virajkaram** [winter-telescope/winterdrp#36]
Make sure the dataframe fields match with the spreadsheet

**Comment by sukishore12** [comment]
Updated and mostly fixed with #77 #18.
Issue still requires a detailed final field-by-field confirmation and updating [spreadsheet](https://docs.google.com/spreadsheets/d/1yEHiD6C787pt0QPsMi1O09IkWE2xy6Itu5wmcL5q5Fo/edit?usp=sharing).
