### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/winterdrp#45]
Extra python requirements were introduced in #39 , but these are not yet reflected in `requirements.txt`/`setup.py`.

At a minimum, `confluent_kafka` is now required, I didn't investigate further yet.

**Comment by sukishore12** [comment]
Looks like `requirements.txt` and 'setup.py' both now include `avro-python3~=1.10.1`, `confluent_kafka`, and `fastavro` -- the three requirements needed for AvroPacketMaker.
