### ISSUE TITLE
Pull out database schema to summer directory

### ISSUE THREAD

**Issue by robertdstein** [winter-telescope/winterdrp#78]
Right now the summer files are distributed across the repo in a way that is difficult to track. We should move all the summer-specific .sql files to the summer directory.

**Comment by virajkaram** [comment]
Aren't all summer specific .sql files here - https://github.com/winter-telescope/winterdrp/tree/main/winterdrp/pipelines/summer/summer_files/schema

**Comment by robertdstein** [comment]
Ah then what are https://github.com/winter-telescope/winterdrp/tree/main/winterdrp/processors/database/schema? Maybe we just need to delete them and we're done?

**Comment by virajkaram** [comment]
Yeah those were very old versions that aren't being used anywhere, need to get rid of them
