### ISSUE TITLE
Add magdifflim field to df 

### ISSUE THREAD

**Issue by sukishore12** [winter-telescope/winterdrp#88]
`magdifflim` is a field used by photometry creation (sections that need it are currently being skipped). Once added, `make_photometry` method in `SendToFritz.py` can be updated.

**Comment by sukishore12** [comment]
`isdiffpos` is also used in the [method](https://github.com/winter-telescope/winterdrp/blob/main/winterdrp/processors/send_to_fritz.py#L454)  and should be added to df

**Comment by virajkaram** [comment]
#91
